# Generated by Django 4.2.4 on 2023-08-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_author'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
