# Generated by Django 4.1.10 on 2023-08-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
